### ISSUE TITLE
Feature request: Delete posts of bots and Ban bot inviters

### ISSUE THREAD

**Issue by hossaink** [group-butler/GroupButler#429] opened 2019-03-04 12:29 UTC
1. The GroupButler has this great feature that kicks any bot; the problem is in the milliseconds-gap between adding the spammer bot and GroupButler kicking it; the spammer sometimes sends some posts that require manual deletion.
2. Moreover, if it was possible to ban the users who add bots to the group immediately; it would be great.

**Comment by NotAFile** [comment] 2019-03-04 13:01
bots can not see other bots messages

**Comment by hossaink** [comment] 2019-03-04 13:06
Thanks for the comment... Interesting limitation by Telegram!
How about the second feature, kicking the one who adds a bot, is it feasible?

**Comment by NotAFile** [comment] 2019-03-04 14:58
I recall this already being a feature

**Comment by alim1369** [comment] 2019-03-04 22:44
I didn't find this feature. it is also good if you remove or mute the parent hierarchy of the robot

**Comment by alim1369** [comment] 2019-03-04 22:46
I have a suggestion for finding the id of messages from other robots.
each message in super groups have an incremental id so if you find a message which the last id is different it means that the message is for the robot and you can remove it.

**Comment by alim1369** [comment] 2019-03-04 23:41
I checked this method and it is not possible to remove other robot's message

**Comment by yangm97** [comment] 2019-03-16 15:51
Dupe of #385

**Closed by yangm97** 2019-03-16 15:51 UTC
