### ISSUE TITLE
Log Channel Lang Changes Randomly

### ISSUE THREAD

**Issue by Fathurhoho** [group-butler/GroupButler#381] opened 2018-10-01 12:54 UTC
Our log channel language changes randomly when #new_member (or might be happen with another even also).

I did not changed the language both in group and bot. 
Our log channel link: https://t.me/joinchat/AAAAAEOk8YGR_buHEest6Q

**Comment by NotAFile** [comment] 2018-10-01 13:06
sounds like a race condition with the current language value...

**Comment by yangm97** [comment] 2018-10-02 02:16
Duplicate of #361

**Closed by yangm97** 2018-10-02 02:16 UTC
